/*
 * Copyright (c) 2014  Akila Ranasinghe </ SPYD3R-X >
 * All rights reserved.
 * GitHub: https://github.com/SPYD3R-X
 * 09 Nov 2014 08:36:10 PM By AKILA.
 */
package UI;

import com.alee.extended.layout.HorizontalFlowLayout;
import com.alee.laf.menu.WebMenuItem;
import com.alee.laf.menu.WebPopupMenu;
import com.alee.managers.tooltip.TooltipManager;
import com.alee.managers.tooltip.TooltipWay;
import com.sun.java.swing.plaf.windows.WindowsButtonUI;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedInputStream;
import java.io.IOException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFrame;
import javax.swing.JProgressBar;
import javax.swing.Timer;

/**
 *
 * @author AKILA
 */
public class Alarm_UI extends javax.swing.JFrame {

    /**
     * Creates new form Alarm_UI
     */
    int Xmouse, Ymouse;

    public Alarm_UI() {
        initComponents();
        setclock();
        setuis();
        seticon();
        countDown();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seted_time = new javax.swing.JLabel();
        lb_currently_state = new javax.swing.JLabel();
        txt_tone_no = new javax.swing.JLabel();
        lb_seconds = new javax.swing.JLabel();
        settings_tn = new javax.swing.JLabel();
        settings_ampm = new javax.swing.JLabel();
        settings_min = new javax.swing.JLabel();
        settings_hr = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lb_time = new javax.swing.JLabel();
        lb_am = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        lb_month = new javax.swing.JLabel();
        lb_day = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();
        btn_about = new javax.swing.JButton();
        btn_setTheme = new javax.swing.JButton();
        txt_on_off = new javax.swing.JLabel();
        txt_alm_timeviewer = new javax.swing.JLabel();
        btn_alarmSettings = new javax.swing.JButton();
        btn_on_off = new javax.swing.JButton();
        wall1 = new javax.swing.JLabel();
        wall2 = new javax.swing.JLabel();
        wall3 = new javax.swing.JLabel();
        wall4 = new javax.swing.JLabel();
        txt_milisec = new javax.swing.JLabel();
        btn_count_on = new javax.swing.JButton();
        lb_check = new javax.swing.JLabel();

        seted_time.setText("seted");

        lb_currently_state.setText("off");

        txt_tone_no.setText("0");

        lb_seconds.setText("sec");

        settings_tn.setText("jLabel4");

        settings_ampm.setText("jLabel3");

        settings_min.setText("jLabel2");

        settings_hr.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Digital Alarm");
        setUndecorated(true);
        setOpacity(0.85F);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_time.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        lb_time.setText("00:00");
        jPanel1.add(lb_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, -1));

        lb_am.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lb_am.setText("AM");
        jPanel1.add(lb_am, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 50));

        lb_date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_date.setText("00");
        jPanel1.add(lb_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        lb_month.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_month.setText("Month");
        jPanel1.add(lb_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 110, -1));

        lb_day.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_day.setText("Day");
        jPanel1.add(lb_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 110, -1));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close_B.png"))); // NOI18N
        btn_close.setContentAreaFilled(false);
        btn_close.setFocusPainted(false);
        btn_close.setFocusable(false);
        btn_close.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close_A.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closeMouseEntered(evt);
            }
        });
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 20, -1));

        btn_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/information.png"))); // NOI18N
        btn_about.setContentAreaFilled(false);
        btn_about.setFocusPainted(false);
        btn_about.setFocusable(false);
        btn_about.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/information_2.png"))); // NOI18N
        btn_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_aboutMouseEntered(evt);
            }
        });
        btn_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 20, -1));

        btn_setTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/theme2.png"))); // NOI18N
        btn_setTheme.setContentAreaFilled(false);
        btn_setTheme.setFocusPainted(false);
        btn_setTheme.setFocusable(false);
        btn_setTheme.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/theme1.png"))); // NOI18N
        btn_setTheme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_setThemeMouseEntered(evt);
            }
        });
        btn_setTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setThemeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_setTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 20, -1));

        txt_on_off.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_on_off.setText("Alarm off");
        jPanel1.add(txt_on_off, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txt_alm_timeviewer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_alm_timeviewer.setText("00:00   ");
        jPanel1.add(txt_alm_timeviewer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 60, -1));

        btn_alarmSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alarm_clock1.png"))); // NOI18N
        btn_alarmSettings.setContentAreaFilled(false);
        btn_alarmSettings.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alarm_clock2.png"))); // NOI18N
        btn_alarmSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_alarmSettingsMouseEntered(evt);
            }
        });
        btn_alarmSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alarmSettingsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_alarmSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        btn_on_off.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_on_off.setText("Off");
        btn_on_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_on_offActionPerformed(evt);
            }
        });
        jPanel1.add(btn_on_off, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, -1));

        wall1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall1.jpg"))); // NOI18N
        jPanel1.add(wall1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 180));

        wall2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall2.jpg"))); // NOI18N
        jPanel1.add(wall2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 180));

        wall3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall3.jpg"))); // NOI18N
        jPanel1.add(wall3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 260, 180));

        wall4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall4.png"))); // NOI18N
        wall4.setText("jLabel1");
        jPanel1.add(wall4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 180));

        txt_milisec.setText("mili");
        jPanel1.add(txt_milisec, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        btn_count_on.setText("jButton1");
        btn_count_on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_count_onActionPerformed(evt);
            }
        });
        jPanel1.add(btn_count_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 60, 10, -1));

        lb_check.setText("nac");
        jPanel1.add(lb_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed

        final JFrame frame = this;
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    String val;
                    for (int i = 9; i > -1; i--) {
                        val = "0." + i;
                        frame.setOpacity(Float.parseFloat(val));
                        Thread.sleep(50);
                    }
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
                System.exit(0);
            }
        }).start();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_alarmSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alarmSettingsActionPerformed

        new Settings_UI(this, true).setVisible(true);

    }//GEN-LAST:event_btn_alarmSettingsActionPerformed

    private void btn_on_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_on_offActionPerformed

        txt_on_off.setVisible(true);
        btn_on_off.setVisible(false);
        btn_alarmSettings.setEnabled(true);
        txt_on_off.setText("Alarm off");
        txt_alm_timeviewer.setText("00:00   ");
        lb_currently_state.setText("on");

    }//GEN-LAST:event_btn_on_offActionPerformed

    private void btn_count_onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_count_onActionPerformed

        countDown();
    }//GEN-LAST:event_btn_count_onActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - Xmouse, y - Ymouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

        Xmouse = evt.getX();
        Ymouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btn_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aboutActionPerformed

        new About(null, true).setVisible(true);
    }//GEN-LAST:event_btn_aboutActionPerformed

    private void btn_setThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setThemeActionPerformed

        // Set Selected Theme
        final WebPopupMenu pop = new WebPopupMenu();
        pop.setMargin(3);
        pop.setLayout(new HorizontalFlowLayout());

        WebMenuItem theme1 = new WebMenuItem("Theme1");
        WebMenuItem theme2 = new WebMenuItem("Theme2");
        WebMenuItem theme3 = new WebMenuItem("Theme3");
        WebMenuItem theme4 = new WebMenuItem("Theme4");
        theme1.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                wall1.setVisible(true);
                wall2.setVisible(false);
                wall3.setVisible(false);
                wall4.setVisible(false);
                lb_am.setForeground(Color.BLACK);
                lb_date.setForeground(Color.BLACK);
                lb_day.setForeground(Color.BLACK);
                lb_month.setForeground(Color.BLACK);
                lb_time.setForeground(Color.BLACK);
            }
        });
        theme2.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                wall1.setVisible(false);
                wall2.setVisible(true);
                wall3.setVisible(false);
                wall4.setVisible(false);
                lb_am.setForeground(Color.WHITE);
                lb_date.setForeground(Color.WHITE);
                lb_day.setForeground(Color.WHITE);
                lb_month.setForeground(Color.WHITE);
                lb_time.setForeground(Color.WHITE);
            }
        });
        theme3.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                wall1.setVisible(false);
                wall2.setVisible(false);
                wall3.setVisible(true);
                wall4.setVisible(false);
                lb_am.setForeground(Color.BLACK);
                lb_date.setForeground(Color.BLACK);
                lb_day.setForeground(Color.BLACK);
                lb_month.setForeground(Color.BLACK);
                lb_time.setForeground(Color.BLACK);
            }
        });
        theme4.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                wall1.setVisible(false);
                wall2.setVisible(false);
                wall3.setVisible(false);
                wall4.setVisible(true);
                lb_am.setForeground(Color.BLACK);
                lb_date.setForeground(Color.BLACK);
                lb_day.setForeground(Color.BLACK);
                lb_month.setForeground(Color.BLACK);
                lb_time.setForeground(Color.BLACK);
            }
        });
        pop.add(theme1);
        pop.add(theme2);
        pop.add(theme3);
        pop.add(theme4);
        pop.showBelowMiddle((Component) evt.getSource());

    }//GEN-LAST:event_btn_setThemeActionPerformed

    private void btn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseEntered
        TooltipManager.setTooltip(btn_close, "Close", TooltipWay.down, 0);
    }//GEN-LAST:event_btn_closeMouseEntered

    private void btn_setThemeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_setThemeMouseEntered
        TooltipManager.setTooltip(btn_setTheme, "Theme", TooltipWay.down, 0);
    }//GEN-LAST:event_btn_setThemeMouseEntered

    private void btn_aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseEntered
        TooltipManager.setTooltip(btn_about, "About", TooltipWay.down, 0);
    }//GEN-LAST:event_btn_aboutMouseEntered

    private void btn_alarmSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_alarmSettingsMouseEntered
        TooltipManager.setTooltip(btn_alarmSettings, "Set Alarm", TooltipWay.up, 0);
    }//GEN-LAST:event_btn_alarmSettingsMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alarm_UI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alarm_UI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alarm_UI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alarm_UI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Alarm_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_about;
    private javax.swing.JButton btn_alarmSettings;
    private javax.swing.JButton btn_close;
    public static javax.swing.JButton btn_count_on;
    public static javax.swing.JButton btn_on_off;
    private javax.swing.JButton btn_setTheme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_am;
    public static javax.swing.JLabel lb_check;
    public static javax.swing.JLabel lb_currently_state;
    private javax.swing.JLabel lb_date;
    private javax.swing.JLabel lb_day;
    private javax.swing.JLabel lb_month;
    public static javax.swing.JLabel lb_seconds;
    private javax.swing.JLabel lb_time;
    public static javax.swing.JLabel seted_time;
    public static javax.swing.JLabel settings_ampm;
    public static javax.swing.JLabel settings_hr;
    public static javax.swing.JLabel settings_min;
    public static javax.swing.JLabel settings_tn;
    public static javax.swing.JLabel txt_alm_timeviewer;
    private javax.swing.JLabel txt_milisec;
    public static javax.swing.JLabel txt_on_off;
    public static javax.swing.JLabel txt_tone_no;
    private javax.swing.JLabel wall1;
    private javax.swing.JLabel wall2;
    private javax.swing.JLabel wall3;
    private javax.swing.JLabel wall4;
    // End of variables declaration//GEN-END:variables

    Date dtCLOCK = new Date();

    private void setclock() {
        try {
            new Timer(0, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {

                    lb_date.setText(new SimpleDateFormat("dd").format(dtCLOCK));
                    lb_day.setText(new SimpleDateFormat("EEEE").format(dtCLOCK));
                    lb_month.setText(new SimpleDateFormat("MMMM").format(dtCLOCK));
                    lb_time.setText(new SimpleDateFormat("hh:mm").format(dtCLOCK));
                    lb_am.setText(new SimpleDateFormat("a").format(dtCLOCK));
                    lb_seconds.setText(new SimpleDateFormat("ss").format(dtCLOCK));
                    txt_milisec.setText(new SimpleDateFormat("SSS").format(dtCLOCK));

                }
            }).start();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setuis() {

        btn_close.setUI(new WindowsButtonUI());
        btn_alarmSettings.setUI(new WindowsButtonUI());
        btn_about.setUI(new WindowsButtonUI());
        btn_setTheme.setUI(new WindowsButtonUI());
        btn_close.setContentAreaFilled(false);
        btn_alarmSettings.setContentAreaFilled(false);
        btn_about.setContentAreaFilled(false);
        btn_setTheme.setContentAreaFilled(false);
        btn_close.setFocusPainted(false);
        btn_alarmSettings.setFocusPainted(false);
        btn_about.setFocusPainted(false);
        btn_setTheme.setFocusPainted(false);
        lb_seconds.setVisible(false);
        btn_on_off.setVisible(false);

    }

    private void seticon() {
        try {
            setIconImage(ImageIO.read(new BufferedInputStream(getClass().getResourceAsStream("/Images/alarm_clock_toolbar.png"))));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    private void countDown() {

        new Thread(new Runnable() {
            @Override
            public void run() {

                try {
                    JProgressBar prog = new JProgressBar(0, 60);
                    for (int i = 0; i <= prog.getMaximum(); i++) {
                        prog.setValue(i);
                        setAlarm_ON();
                        Thread.sleep(1000);
                    }
                    countDown();

                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }

            }
        }).start();
    }

    private void setAlarm_ON() {
        String currenttime = lb_time.getText() + "-" + lb_am.getText();
        String setedtime = seted_time.getText();

        if (currenttime.equals(setedtime)) {
            try {
                btn_on_off.setVisible(true);
                btn_alarmSettings.setEnabled(false);
                txt_on_off.setVisible(false);
                JProgressBar prog = new JProgressBar(0, 60);
                for (int i = 0; i <= prog.getMaximum(); i++) {
                    prog.setValue(i);

                    String bt = "on";
                    String txt = lb_currently_state.getText();
                    if (txt.equals(bt)) {
                        Thread.currentThread().stop();
                    } else {
                        // Play Alarm-Audio...
                        int alarmTone = Integer.valueOf(txt_tone_no.getText());
                        if (alarmTone == 0) {
                            playSound1();
                        }
                        if (alarmTone == 1) {
                            playSound2();
                        }
                        if (alarmTone == 2) {
                            playSound3();
                        }
                    }
                    Thread.sleep(1780);
                }
                countDown();
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
        }
    }

    public void playSound1() {

        try {
            URL url = this.getClass().getResource("/Audio/alarm1.wav");
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
            Clip clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            System.out.println(e);
        }
    }

    public void playSound2() {

        try {
            URL url = this.getClass().getResource("/Audio/alarm2.wav");
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
            Clip clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            System.out.println(e);
        }
    }

    public void playSound3() {

        try {
            URL url = this.getClass().getResource("/Audio/alarm3.wav");
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
            Clip clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            System.out.println(e);
        }
    }
}
